### ISSUE TITLE
Removing modules in space while running keeps their benefits

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#77]
Undock an Orca.  Equip multiple Invulnerability Fields, activate them.  Open the fitting window, and unfit the modules.  You briefly see an error saying you can't offline a module while it's running.  You retain the bonuses of the running module.  Requip them, repeat until you have 99.99% resistances :) 
![Capture](https://user-images.githubusercontent.com/51723245/70018267-35f1f000-154b-11ea-9d33-c7aa7a31333c.PNG)

**Comment by zhyrohaad** [comment]
wow
that's interesting to say the least.
on the plus side, dock or relog will reset ship to default then recalculate mods.

i have found multiple errors in module code while tracking recent bugs.
im updating main with fixes as i get them done, but this may lead to other bugs.
this is a case-in-point....woudlnt have known this before #19 was fixed.  lol

most of the bugs are things i didnt (or wont) think of.

** update **
this was an easy fix.  modules call Offline() before removal and  the code for checking module states when calling a state change was already in place (and use for function testing logs).  i added call to stop cycle before offline in this case.  done.

**Comment by zhyrohaad** [comment]
fixed and main updated.

**Comment by ryllae** [comment]
Still broken.  I get a "your invulerabilty field must finish its cycle before going offline" error, and I still get the bonus when I click the "unfit" radial button. The CPU consumption is also remains present from the "phantom module".  

On the plus side, I also broke 1.2 trillion EHP on my Orca without too much effort.
![Annotation 2019-12-03 205639](https://user-images.githubusercontent.com/51723245/70108866-f2ad8500-160f-11ea-84eb-96e48910b08c.png)

**Comment by zhyrohaad** [comment]
yeah.....i forgot to restart after compiling update.
updated now.

**Comment by ryllae** [comment]
fixed!
